version: "3.8"

services:
  auth-app:
    container_name: auth-services
    build:
      context: ./auth
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
      - 5000:5000
    volumes:
      - ./auth/:/app
    environment:
      env_file: ./auth/.env
    networks:
      - chat-network

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_SECRET_ACCESS_KEY=secret_access_key
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack:/tmp/localstack"
    networks:
      - chat-network

networks:
  - chat-network:
    external: true      
