version: "3.8"

services:
  auth-app:
    container_name: auth-services
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    environment:
      env_file: .env
    networks:
      - chat-network

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_SECRET_ACCESS_KEY=secret_access_key
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack:/tmp/localstack"
    networks:
      - chat-network

networks:
  - chat-network:
    external: true      
